apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app

spec:
  replicas: 2

  env:
  - name: VITE_APP_URL
    valueFrom:
      configMapKeyRef:
        name: react-config
        key: VITE_APP_URL

  selector:
    matchLabels:
      app: react-app

  template:
    metadata:
      labels:
        app: react-app

    spec:
      containers:
      - name: react-app
        image: 584868043218.dkr.ecr.us-east-1.amazonaws.com/react-app:latest

        ports:
        - containerPort: 80 