name: CI-CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3


      # 🔐 Configure AWS Credentials
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}


      # 🔐 Login to ECR (IMPORTANT)
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1


      # 🐳 Build Docker Image
      - name: Build Image
        run: |
          docker build \
            --no-cache \
            --build-arg VITE_APP_URL=https://fakestoreapi.com \
            -t react-app:${{ github.sha }} \
            .

      # 🏷️ Tag Image
      - name: Tag Image
        run: |
          docker tag react-app:${{ github.sha }} \
          ${{ secrets.ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/react-app:${{ github.sha }}


      # 🚀 Push Image
      - name: Push Image
        run: |
          docker push \
          ${{ secrets.ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/react-app:${{ github.sha }}

      # 📦 Deploy to Kubernetes

      
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
          --region ${{ secrets.AWS_REGION }} \
          --name react-app-cluster
      
      - name: Update Deployment Image
        run: |
          kubectl set image deployment/react-app \
          react-app=${{ secrets.ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/react-app:${{ github.sha }}


      - name: Deploy to Kubernetes
        run: |
          
          kubectl apply -f k8s/manifests/service.yml
          kubectl apply -f k8s/manifests/ingress.yml
          kubectl apply -f k8s/manifests/hpa.yml